default: &default
    adapter: postgresql
    encoding: unicode
    host: <%= ENV["DB_HOST"] || "localhost" %>
    username: postgres
    password: password
    pool: 5

development:
    <<: *default
    database: testapp_development

test:
    <<: *default
    database: testapp_test
