version: "3.7"

services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password